trigger:
  branches:
    exclude:
      - '*'

pool:
  vmImage: 'windows-latest'

steps:
- script: |
    git config --global user.email "yogesh.dhole@spurqlabs.com"
    git config --global user.name "ydhole-spurqlabs"
  displayName: 'Set Git Config'

- checkout: self

- script: |
    git remote add github https://ydhole-spurqlabs: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@github.com/spurqlabs/TodoApiExampleBackup.git
    git push github --mirror --force
  displayName: 'Push to GitHub'