# trigger:
#   branches:
#     exclude:
#       - '*'

# pool:
#   vmImage: 'windows-latest'

# variables:
#   - name: GitHubUsername
#     value: 'ydhole-spurqlabs'
#   - name: GitHubPAT
#     value: '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'

# steps:
# - script: |
#     git config --global user.email "yogesh.dhole@spurqlabs.com"
#     git config --global user.name "ydhole-spurqlabs"
#   displayName: 'Set Git Config'

# - checkout: self

# - script: |
#     git remote add github https://$(GitHubUsername):$(GitHubPAT)@github.com/spurqlabs/TodoApiExampleBackup.git
#     git push github --mirror --force
#   displayName: 'Push to GitHub'


#Azure-pipeline.yml for reference
# trigger:
# - master

# pool:
#   vmImage: ubuntu-latest

# steps:
# - checkout: self
# - bash: |
#     git remote add origin_with_token https://ydhole-spurqlabs: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@github.com/spurqlabs/TodoApiExample
#     git push --prune origin_with_token --all
#     git push --prune origin_with_token --tags
#   displayName: 'to GitHub'
#   condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')






trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  GitHubUsername: ydhole-spurqlabs
  GitHubPAT: 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

steps:
- checkout: self

- bash: |
    git remote add origin_with_token https://${{ variables.GitHubUsername }}:${{ variables.GitHubPAT }}@github.com/spurqlabs/TodoApiExample
    git push origin_with_token --all
    git push origin_with_token --tags
  displayName: 'Push to GitHub'

- bash: |
    echo "Current branch: $(Build.SourceBranch)"
    echo "Condition result: ${{ eq(variables['Build.SourceBranch'], 'refs/heads/master') }}"
  displayName: 'Debug Information'

  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')


