trigger:
  branches:
    exclude:
      - '*'

pool:
  vmImage: 'windows-latest'

variables:
  - name: GitHubUsername
    value: 'ydhole-spurqlabs'

steps:
  - script: |
      git config --global user.email "yogesh.dhole@spurqlabs.com"
      git config --global user.name "ydhole-spurqlabs"
    displayName: 'Set Git Config'

  - checkout: self

  - script: |
      git remote add github https://$(GitHubUsername):${{ secrets.PAT }}@github.com/ydhole-spurqlabs/backuprepo
      git push github --mirror --force
    displayName: 'Push to GitHub'
